server:
  port: ${APP_PORT:8090}
  servlet:
    session:
      persistent: false
      timeout: 0
spring:
  servlet:
    multipart:
      max-file-size: ${SERVER_LIMIT_UPLOAD_SIZE:512MB}
      max-request-size: ${SERVER_LIMIT_REQUEST_SIZE:512MB}
      enabled: ${SERVER_MULTIPART_ENABLED:true}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:jaksmok}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
  mvc:
    throw-exception-if-no-handler-found: true

jwt:
  secret: ${JWT_SECRET_KEY:locale-server-123456}

logging:
  level:

    jdbc:
      sqltiming: ${LOGGING_JDBC_SHOW_SQL:info}
      resultsettable: off
      resultset: off
      audit: off
      sqlonly: off
      connection: off

